### ISSUE TITLE
Right side sidebar not showing

### ISSUE THREAD

**Issue by Draichi** [creativetimofficial/vue-black-dashboard#2]
Hey, very nice project.

I'm having a issue though,

This sidebar
![fixed_dropdown](https://user-images.githubusercontent.com/19378148/55918888-36a7d180-5bca-11e9-9277-470c7b289b67.png) is not showing, it seems that the free version also have this feature because of the link in this project https://demos.creative-tim.com/vue-black-dashboard/#/dashboard

I just cloned the project, didn't change anything, but is not showing.
What do I have to do?

Thanks

**Comment by sbrian26** [comment]
Fyi - The sidebar gear is active in the live-demo branch.

**Comment by sbrian26** [comment]
Do you not know how to change branches of the repository? Otherwise I don't understand your thumbs down? Change branches and see the SideBarSharePlugin.vue, etc. It has the feature you're looking for.

**Comment by Craig-Burch** [comment]
Got em!

**Comment by JJSeah** [comment]
> Do you not know how to change branches of the repository? Otherwise I don't understand your thumbs down? Change branches and see the SideBarSharePlugin.vue, etc. It has the feature you're looking for which have not yet been merged into the main branch.

Proceed to the code tab and right below it should be commits and branches. Click on branches to choose another branch.
