### ISSUE TITLE
How increase font for all web app?

### ISSUE THREAD

**Issue by tolyanor** [creativetimofficial/vue-black-dashboard#5]
How increase font for all web app?

I try
```
  body {
    font-size: 15px;
  }
```
but it not worked for me.
Also how change dark to light theme on the fly?

Thanks!

**Comment by JJSeah** [comment]
I think to change the font-size you would have to change the main css file. 

To change dark to light mode I made use of this function, in my dashboardnavbar.vue. 
 toggleMode() {
        let docClasses = document.body.classList;
        if (this.themes === false) {
          docClasses.add('white-content')
        } else {
          docClasses.remove('white-content')
        }
      },

Hope this helps
